JWT Integration Test
burnt-labs/xion pull request #129
Opened 2023-10-18 17:45 UTC by ash-burnt

2023-10-18 18:50 UTC, edjroz requested changes

2023-10-18 18:52 UTC, edjroz commented on integration_tests/abstract_account_test.go
> +	fmt.Println("=======================================================")
Debugging line, should be removed
```suggestion
```

2023-10-18 20:50 UTC, froch commented on x/xion/client/cli/tx.go
> +		Args:  cobra.ExactArgs(3),
```suggestion
		Args:  cobra.ExactArgs(1),
```

2023-10-18 20:52 UTC, froch commented on x/xion/client/cli/tx.go
> +// NewSendTxCmd returns a CLI command handler for creating a MsgSend transaction.
```suggestion
// NewSignCmd returns a CLI command to sign a Tx with the Smart Contract Account signer
```

2023-12-14 16:31 UTC, edjroz approved these changes

2023-12-14 16:31 UTC, merged