Feat/auto passkey
burnt-labs/xion pull request #207
Opened 2024-05-14 08:07 UTC by Peartes

This PR makes it possible to generate WebAuthN credentials and assertions for the integration test. This removes the hassle of updating the test every time the hash of the contract changes

2024-05-14 14:55 UTC, ash-burnt approved these changes

2024-05-14 16:52 UTC, ash-burnt requested changes

2024-05-14 16:52 UTC, ash-burnt commented on wasmbindings/test_utils.go
> +	"github.com/golang-jwt/jwt/v5"
Please rewrite this with lestrrat-go, you can use the query handler as an example. We don't want to have two distinct jwk/t libraries in use

2024-05-14 22:40 UTC, ash-burnt approved these changes

2024-05-15 17:12 UTC, justinbarry commented on x/xion/types/webauthn_test.go
> +	privateKey, _, err := wasmbinding.SetupPublicKeys("../../../wasmbindings/keys/jwtRS256.key")
Do we need two jwtRS256.key files?

2024-05-15 17:20 UTC, justinbarry approved these changes
LGTM

2024-05-21 22:16 UTC, merged