Enable wasm light clients
burnt-labs/xion pull request #258
Opened 2024-09-19 00:36 UTC by ash-burnt

2024-09-20 16:19 UTC, 2xburnt approved these changes

2024-09-30 16:41 UTC, edjroz submitted a review, later dismissed

2024-09-30 16:41 UTC, edjroz commented on app/app.go
> +		WasmContractMemoryLimit, // default of 32
I'm gonna sound like a teacher, but 32 Bytes? KB? MB? GB?

2024-10-01 03:11 UTC, edjroz requested changes
Integration test needs to mark version we are going to in the file `integration_tests/upgrade_ibc_test.go`

```
...
xionVersionTo   = "<correct_sha>"
xionUpgradeName = "v12"
```
as it is a constant to keep up with the tests accross upgrades.

2024-10-01 11:38 UTC, ash-burnt commented
@edjroz I updated the upgrade version, but there isn't a correct sha to set it to, because the heighliner CI isn't building releases currently. Once it is live again, it will be doable

2024-10-01 15:05 UTC, edjroz approved these changes

2024-10-01 15:52 UTC, justinbarry approved these changes
LGTM

2024-10-01 15:57 UTC, merged